version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/app"
      - "/test"
    schedule:
      interval: "daily"
    assignees:
      - "ytgw"
    cooldown:
      default-days: 14
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ytgw"
    cooldown:
      default-days: 14
